### ISSUE TITLE
modules problem browserify v13

### ISSUE THREAD

**Issue by coderofsalvation** [garthenweb/bubleify#11]
I get this:

```[10:00:32] Error: Parsing file /foo/bar/assets/js/app.js: 'import' and 'export' may appear only with 'sourceType: module' (24:0)```

When trying to compile a file with 'import' with these settings:

      .transform(bubleify, {
        target: {
          chrome: 48,
          firefox: 44,
        },
        transforms: {
          modules: false,                                <-- didn't help either
          arrow: true,
          defaultParameter: false,
          dangerousForOf: true
        },
      })
      .bundle()                      <-- this triggers the error

Using Browserify v13.1.1.
Any ideas?

**Comment by garthenweb** [comment]
The `import` statements is neither in the scope of browserify nor of buble, thus bubleify does not support it. I would say your options are
* using [rollupify](https://github.com/nolanlawson/rollupify) to transform `import` and `export` statements
* go with CommonJS and the plain old require function.
