### ISSUE TITLE
sourcemaps

### ISSUE THREAD

**Issue by tunnckoCore** [garthenweb/bubleify#12]
I believe it should use `result.map.toUrl()` only when `options.sourcemap` is `inline`, otherwise `result.map.toString()` or i'm wrong?

**Comment by garthenweb** [comment]
What would be the benefit of using the `toString` method? Can you explain what it actually returns in comparison to `toURL`?

**Comment by tunnckoCore** [comment]
I believe (if i'm not wrong, because I'm not so sourcemap/frontend guy), it's a convention `.toUrl` to return path to where the actual map in JSON.stringified format. And `.toString()` returns base64 in the same file. That's the whole point of that separation and sourcemaps at al.

**Comment by garthenweb** [comment]
I cannot tell if its a convention, but for buble its the opposite: `toUrl` returns the source map as base64 string. `toString` would return the plain source map that could be written into another file.

You can have a look how buble originally handles this here: https://gitlab.com/Rich-Harris/buble/blob/master/bin/runBuble.js#L58

Bubleify at the moment does not support externalization of the source maps, so `inline` is the default.
I recommend to use tools like [uglify](https://github.com/mishoo/UglifyJS2) or [exorcist](https://github.com/thlorenz/exorcist) to extract the source map into another file if required.

At the moment I also do not see any demand to add such a feature. Anyhow, if anyone is interested in an externalization handled by bubleify I will be happy to receive a merge request.

For now I will close this issue as long as it does not have a clear purpose. Please feel free to ask further questions if you have some!
