### ISSUE TITLE
Considering buble as peer dependency?

### ISSUE THREAD

**Issue by huozhi** [garthenweb/bubleify#15]
benefit:
if buble upgrade itself and compatible with the previous one, users are able to select buble's version themselves.

other examples:
https://github.com/babel/babelify/blob/master/package.json

**Comment by garthenweb** [comment]
I would be happy to receive a PR, in case Buble updates again at some point in time.
If not, I don't think it's a benefit releasing a breaking change like that at all as I currently cannot see any development on the Buble project.

**Comment by huozhi** [comment]
understood.
I think it's ok to keep the current code. since npm will still also be able to install the latest minor version of buble. and buble's size is not that big for installation.

I'll close this issue as the benefit is not enough for such change. Thanks for explanation!
