### ISSUE TITLE
[].inlcudes() only works with node v6

### ISSUE THREAD

**Issue by kevinkace** [garthenweb/bubleify#6]
Could this be transpiled to support node v4?

**Comment by garthenweb** [comment]
Thank you for this hint, I wonder why the tests where passing...
Nevertheless, transpiling is a little bit tricky here. I just replaced it with an `indexOf(foo) === -1` to get rid of it. Please update to v0.5.1 via npm.

**Comment by kevinkace** [comment]
Thanks for the fast response and fix!

Working in node v4.4.5.
